### ISSUE TITLE
Nginx on sso machine sometimes fails with cert after reboot

### ISSUE THREAD

**Issue by tswfi** [hacklab-fi/itinfra#24]
Can't remember the exact details right now, but something about the restart starts services in an order where nginx wont handle ssl cert correctly (maybe dns doesn't resolve when nginx starts?)

This causes firefox to show Mozilla_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING error.

restarting nxingx fixes the problem.

**Comment by tswfi** [comment]
@olmari do you have more details for this?

**Comment by olmari** [comment]
Needs unit file override for starting after Named (so resolver is available) which is needed for proper SSL-cert staple response.

There is still change to this exact error coming once after some reboot or some large amount of time passing, but that is kind of separate issue, even when causes are pretty much because of same "services".

**Comment by olmari** [comment]
Added unit-file override to start after DNS-resolver
